version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/packages/common"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/packages/core"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/packages/events"
    schedule:
      interval: "weekly"
