import { MetadataScope } from '../constant';
export type MetadataKey<K = string | symbol> = K;
export type MetadataValue<T = unknown> = T;
export type MetadataTarget = object | Function;
export type MetadataPropertyKey = string | symbol;
export type MetadataParameterIndex = number;
export type Decorator = ClassDecorator & PropertyDecorator & MethodDecorator & ParameterDecorator;
export type TargetType = 'class' | 'method' | 'function' | 'object' | 'unknown';
export type TargetIdentification = { type: TargetType; target: MetadataTarget };
export type MetadataScopeType = keyof typeof MetadataScope;
